"""
Curated timezone list sorted by UTC offset.
Each entry: (iana_name, friendly_label)
"""

TIMEZONES: list[tuple[str, str]] = [
    ("Pacific/Midway",         "(UTC-11:00) Midway Island, Samoa"),
    ("Pacific/Honolulu",       "(UTC-10:00) Hawaii"),
    ("America/Anchorage",      "(UTC-09:00) Alaska"),
    ("America/Los_Angeles",    "(UTC-08:00) Pacific Time (US & Canada)"),
    ("America/Tijuana",        "(UTC-08:00) Tijuana, Baja California"),
    ("America/Denver",         "(UTC-07:00) Mountain Time (US & Canada)"),
    ("America/Phoenix",        "(UTC-07:00) Arizona"),
    ("America/Chihuahua",      "(UTC-07:00) Chihuahua, La Paz, Mazatlan"),
    ("America/Chicago",        "(UTC-06:00) Central Time (US & Canada)"),
    ("America/Regina",         "(UTC-06:00) Saskatchewan"),
    ("America/Mexico_City",    "(UTC-06:00) Mexico City, Monterrey, Guadalajara"),
    ("America/Guatemala",      "(UTC-06:00) Central America"),
    ("America/New_York",       "(UTC-05:00) Eastern Time (US & Canada)"),
    ("America/Indiana/Indianapolis", "(UTC-05:00) Indiana (East)"),
    ("America/Bogota",         "(UTC-05:00) Bogota, Lima, Quito"),
    ("America/Caracas",        "(UTC-04:00) Caracas"),
    ("America/Halifax",        "(UTC-04:00) Atlantic Time (Canada)"),
    ("America/La_Paz",         "(UTC-04:00) Georgetown, La Paz, Manaus"),
    ("America/Santiago",       "(UTC-04:00) Santiago"),
    ("America/St_Johns",       "(UTC-03:30) Newfoundland"),
    ("America/Sao_Paulo",      "(UTC-03:00) Brasilia"),
    ("America/Argentina/Buenos_Aires", "(UTC-03:00) Buenos Aires"),
    ("America/Godthab",        "(UTC-03:00) Greenland"),
    ("America/Montevideo",     "(UTC-03:00) Montevideo"),
    ("Atlantic/South_Georgia", "(UTC-02:00) Mid-Atlantic"),
    ("Atlantic/Azores",        "(UTC-01:00) Azores"),
    ("Atlantic/Cape_Verde",    "(UTC-01:00) Cape Verde"),
    ("UTC",                    "(UTC+00:00) UTC"),
    ("Europe/London",          "(UTC+00:00) London, Edinburgh, Lisbon, Dublin"),
    ("Africa/Casablanca",      "(UTC+00:00) Casablanca, Monrovia, Reykjavik"),
    ("Europe/Berlin",          "(UTC+01:00) Berlin, Vienna, Brussels, Copenhagen"),
    ("Europe/Paris",           "(UTC+01:00) Paris, Madrid, Amsterdam"),
    ("Europe/Rome",            "(UTC+01:00) Rome, Stockholm, Prague, Warsaw"),
    ("Africa/Lagos",           "(UTC+01:00) West Central Africa"),
    ("Europe/Athens",          "(UTC+02:00) Athens, Bucharest, Istanbul"),
    ("Europe/Helsinki",        "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"),
    ("Europe/Kiev",            "(UTC+02:00) Kyiv"),
    ("Asia/Jerusalem",         "(UTC+02:00) Jerusalem"),
    ("Africa/Cairo",           "(UTC+02:00) Cairo"),
    ("Africa/Johannesburg",    "(UTC+02:00) Harare, Pretoria"),
    ("Asia/Baghdad",           "(UTC+03:00) Baghdad"),
    ("Asia/Riyadh",            "(UTC+03:00) Kuwait, Riyadh"),
    ("Europe/Moscow",          "(UTC+03:00) Moscow, St. Petersburg, Volgograd"),
    ("Africa/Nairobi",         "(UTC+03:00) Nairobi"),
    ("Asia/Tehran",            "(UTC+03:30) Tehran"),
    ("Asia/Dubai",             "(UTC+04:00) Abu Dhabi, Muscat"),
    ("Asia/Baku",              "(UTC+04:00) Baku, Tbilisi, Yerevan"),
    ("Asia/Kabul",             "(UTC+04:30) Kabul"),
    ("Asia/Yekaterinburg",     "(UTC+05:00) Ekaterinburg"),
    ("Asia/Karachi",           "(UTC+05:00) Islamabad, Karachi, Tashkent"),
    ("Asia/Kolkata",           "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi"),
    ("Asia/Colombo",           "(UTC+05:30) Sri Jayawardenepura"),
    ("Asia/Kathmandu",         "(UTC+05:45) Kathmandu"),
    ("Asia/Dhaka",             "(UTC+06:00) Astana, Dhaka"),
    ("Asia/Almaty",            "(UTC+06:00) Almaty, Novosibirsk"),
    ("Asia/Rangoon",           "(UTC+06:30) Yangon (Rangoon)"),
    ("Asia/Bangkok",           "(UTC+07:00) Bangkok, Hanoi, Jakarta"),
    ("Asia/Krasnoyarsk",       "(UTC+07:00) Krasnoyarsk"),
    ("Asia/Shanghai",          "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi"),
    ("Asia/Kuala_Lumpur",      "(UTC+08:00) Kuala Lumpur, Singapore"),
    ("Asia/Taipei",            "(UTC+08:00) Taipei"),
    ("Australia/Perth",        "(UTC+08:00) Perth"),
    ("Asia/Irkutsk",           "(UTC+08:00) Irkutsk, Ulaanbaatar"),
    ("Asia/Seoul",             "(UTC+09:00) Seoul"),
    ("Asia/Tokyo",             "(UTC+09:00) Osaka, Sapporo, Tokyo"),
    ("Asia/Yakutsk",           "(UTC+09:00) Yakutsk"),
    ("Australia/Adelaide",     "(UTC+09:30) Adelaide"),
    ("Australia/Darwin",       "(UTC+09:30) Darwin"),
    ("Australia/Brisbane",     "(UTC+10:00) Brisbane"),
    ("Australia/Sydney",       "(UTC+10:00) Canberra, Melbourne, Sydney"),
    ("Pacific/Guam",           "(UTC+10:00) Guam, Port Moresby"),
    ("Australia/Hobart",       "(UTC+10:00) Hobart"),
    ("Asia/Vladivostok",       "(UTC+10:00) Vladivostok"),
    ("Asia/Magadan",           "(UTC+11:00) Magadan, Solomon Islands, New Caledonia"),
    ("Pacific/Auckland",       "(UTC+12:00) Auckland, Wellington"),
    ("Pacific/Fiji",           "(UTC+12:00) Fiji, Marshall Islands"),
    ("Pacific/Tongatapu",      "(UTC+13:00) Nuku'alofa"),
]

TIMEZONE_NAMES = [iana for iana, _ in TIMEZONES]
